### ISSUE TITLE
blur not working with optifine

### ISSUE THREAD

**Issue by WuschelWookie** [Cheaterpaul/ReBlured#2]
Hello, I am using your mod on version 1.19.2 and it also worked fine at first. But as soon as I installed Optifine, it didnt work anymore. I tried it without a shader but as long as I use Optifine, it just wont work. Any suggestions?

**Comment by Cheaterpaul** [comment]
Works fine for me even with shader. What Optifine version and shader are you using?

**Comment by WuschelWookie** [comment]
I am using forge-43.1.1 and OptiFine HD U H9 and the ComplementaryShaders_v4.6

**Comment by Cheaterpaul** [comment]
Do you have Antialiasing on in the shader settings? It will override the blur effect.

**Comment by WuschelWookie** [comment]
Thank you. It fixed the problem.

**Comment by rainbowflesh** [comment]
forge 44.1.17 & Optfine HD_U_I2_pre5 not work, even disable shader and antialiasing.

**Comment by Cheaterpaul** [comment]
fixed in the new beta.2
