### ISSUE TITLE
Mod name is spelled incorrectly

### ISSUE THREAD

**Issue by vinnyg0621** [Cheaterpaul/ReBlured#3]
actually, the correct way to spell "blured" is "blurred". so this mod's name should've been spelled "ReBlurred" instead of "ReBlured"

**Comment by vinnyg0621** [comment]
wait, why did you close this as not planned???

**Comment by vinnyg0621** [comment]
> wait, why did you close this as not planned???

why?!?!?!!!! **answer me!!!!**

**Comment by Cheaterpaul** [comment]
Because the mod is named ReBlured and not ReBlurred.

**Comment by vinnyg0621** [comment]
i thought blured was a misspelling of "blurred" >:(
